name: ai_suggestion_app
description: AI Suggestion App with Firebase & OpenAI
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_messaging: ^15.0.0
  http: ^1.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  speech_to_text: ^6.6.0
  flutter_tts: ^3.6.3
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
